-- ============================================================================
-- Migration 004: Source Document Persistence (v5)
-- ============================================================================
-- Adds tables for storing uploaded document metadata and linking them to
-- receipts and purchase orders. Also creates a private Supabase Storage
-- bucket for the actual files.
--
-- Run this in Supabase SQL Editor BEFORE continuing with v5 code changes.
-- ============================================================================

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════
-- TABLE: source_document
-- ═══════════════════════════════════════════════════════════════════════
-- Each row represents one uploaded file (PDF or image). The actual file
-- lives in Supabase Storage; this table stores metadata + the storage path.

CREATE TABLE source_document (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_path     text        NOT NULL,
  original_filename text       NOT NULL,
  mime_type        text        NOT NULL,
  size_bytes       bigint      NOT NULL,
  uploaded_at      timestamptz NOT NULL DEFAULT now(),
  uploaded_via     text        NOT NULL,   -- 'receipt_extraction' | 'order_extraction' | 'manual_attach'
  context          text        NOT NULL    -- 'receipt' | 'order'
);

-- One row per actual file — no duplicates in storage
CREATE UNIQUE INDEX idx_source_document_storage_path ON source_document (storage_path);

-- Enable RLS (permissive for now — no auth in v5)
ALTER TABLE source_document ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to source_document"
  ON source_document FOR ALL
  USING (true)
  WITH CHECK (true);

-- ═══════════════════════════════════════════════════════════════════════
-- JOIN TABLE: receipt_source_document
-- ═══════════════════════════════════════════════════════════════════════
-- Links receipts to their source documents (many-to-many).
-- CASCADE on receipt delete: if receipt is deleted, the link is cleaned up.
-- RESTRICT on source_document delete: can't delete a file still linked.

CREATE TABLE receipt_source_document (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id          bigint NOT NULL REFERENCES receipt(id) ON DELETE CASCADE,
  source_document_id  bigint NOT NULL REFERENCES source_document(id) ON DELETE RESTRICT,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_receipt_source_document_unique
  ON receipt_source_document (receipt_id, source_document_id);

ALTER TABLE receipt_source_document ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to receipt_source_document"
  ON receipt_source_document FOR ALL
  USING (true)
  WITH CHECK (true);

-- ═══════════════════════════════════════════════════════════════════════
-- JOIN TABLE: purchase_order_source_document
-- ═══════════════════════════════════════════════════════════════════════
-- Same pattern as receipt_source_document, for purchase orders.

CREATE TABLE purchase_order_source_document (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id   bigint NOT NULL REFERENCES purchase_order(id) ON DELETE CASCADE,
  source_document_id  bigint NOT NULL REFERENCES source_document(id) ON DELETE RESTRICT,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_purchase_order_source_document_unique
  ON purchase_order_source_document (purchase_order_id, source_document_id);

ALTER TABLE purchase_order_source_document ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to purchase_order_source_document"
  ON purchase_order_source_document FOR ALL
  USING (true)
  WITH CHECK (true);

-- ═══════════════════════════════════════════════════════════════════════
-- STORAGE BUCKET: source-documents (private)
-- ═══════════════════════════════════════════════════════════════════════
-- Private bucket — files are accessed via signed URLs only.
-- The INSERT is idempotent: ON CONFLICT DO NOTHING in case bucket exists.

INSERT INTO storage.buckets (id, name, public)
VALUES ('source-documents', 'source-documents', false)
ON CONFLICT (id) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════
-- STORAGE RLS POLICIES
-- ═══════════════════════════════════════════════════════════════════════
-- Allow service_role full access (used by API routes).
-- Allow anon role read/write access (no auth in v5 — documented risk,
-- consistent with the rest of the app's permissive RLS model).
-- These policies will be tightened in v6 when authentication is added.

-- Policy: service_role can do everything
CREATE POLICY "Service role full access to source-documents"
  ON storage.objects FOR ALL
  TO service_role
  USING (bucket_id = 'source-documents')
  WITH CHECK (bucket_id = 'source-documents');

-- Policy: anon can SELECT (read/download)
CREATE POLICY "Anon read access to source-documents"
  ON storage.objects FOR SELECT
  TO anon
  USING (bucket_id = 'source-documents');

-- Policy: anon can INSERT (upload)
CREATE POLICY "Anon insert access to source-documents"
  ON storage.objects FOR INSERT
  TO anon
  WITH CHECK (bucket_id = 'source-documents');

-- Policy: anon can UPDATE (needed for some storage operations)
CREATE POLICY "Anon update access to source-documents"
  ON storage.objects FOR UPDATE
  TO anon
  USING (bucket_id = 'source-documents')
  WITH CHECK (bucket_id = 'source-documents');

-- Policy: anon can DELETE
CREATE POLICY "Anon delete access to source-documents"
  ON storage.objects FOR DELETE
  TO anon
  USING (bucket_id = 'source-documents');

COMMIT;
